import type { ActivityItem, MediaAsset, Project, Stage } from "./types";
import dims from "@/data/demo-dimensions.json";
import cloudinarySeed from "@/data/cloudinary-seed.json";

export const PROJECTS: (Project & { archivedAssets: number })[] = [
  {
    id: "p-rajasthan-water",
    slug: "rajasthan-water-access",
    name: "Rajasthan Water Access",
    category: "Water & Sanitation",
    location: "Jodhpur, Rajasthan",
    region: "Rajasthan, India",
    description:
      "Community water storage, hand pumps, rainwater harvesting and check dams across arid villages in western Rajasthan.",
    status: "Active",
    startDate: "2026-01-10",
    archivedAssets: 117,
  },
  {
    id: "p-delhi-greening",
    slug: "delhi-urban-greening",
    name: "Delhi Urban Greening",
    category: "Environment",
    location: "New Delhi, Delhi",
    region: "Delhi, India",
    description:
      "Restoration of degraded urban land through waste clean-up, segregation infrastructure and community tree plantation.",
    status: "Active",
    startDate: "2026-01-12",
    archivedAssets: 84,
  },
  {
    id: "p-maharashtra-solar",
    slug: "maharashtra-solar-initiative",
    name: "Maharashtra Solar Initiative",
    category: "Renewable Energy",
    location: "Pune, Maharashtra",
    region: "Maharashtra, India",
    description:
      "Rooftop and ground-mounted solar installations for rural schools and community buildings across western Maharashtra.",
    status: "Active",
    startDate: "2026-01-15",
    archivedAssets: 208,
  },
];

/** Organisation-wide totals that live outside the three demo projects. */
export const ORG_BASELINE = {
  otherAssets: 845,
  fieldSites: 42,
  reports: 18,
  aiCoverage: 0.96,
};

type SeedInput = {
  file: string;
  title: string;
  description: string;
  location: string;
  activity: string;
  tags: string[];
  impactAreas: string[];
  objects: string[];
  peopleCount: number | null;
  stage: Stage;
  date: string;
  confidence: number;
  beforeAfterCandidate?: boolean;
};

const D = dims as unknown as Record<string, [number, number]>;
const CS = cloudinarySeed as unknown as Record<
  string,
  { secureUrl: string; width: number; height: number; format: string; createdAt: string }
>;

function build(project: Project, items: SeedInput[]): MediaAsset[] {
  return items.map((s) => {
    const publicId = `impactlens/demo/${project.slug}/${s.file}`;
    const real = CS[publicId];
    const [w, h] = D[s.file] ?? [1280, 853];
    return {
      id: s.file,
      projectId: project.id,
      cloudinaryPublicId: publicId,
      secureUrl: real?.secureUrl ?? `/demo/${s.file}.jpg`,
      resourceType: "image",
      format: real?.format ?? "jpg",
      width: real?.width ?? w,
      height: real?.height ?? h,
      createdAt: real?.createdAt ?? `${s.date}T09:30:00.000Z`,
      storage: real ? "cloudinary" : "local",
      originalFilename: `${s.file}.jpg`,
      title: s.title,
      description: s.description,
      project: project.name,
      location: s.location,
      category: project.category,
      activity: s.activity,
      tags: s.tags,
      impactAreas: s.impactAreas,
      objects: s.objects,
      peopleCount: s.peopleCount,
      stage: s.stage,
      confidence: s.confidence,
      date: s.date,
      beforeAfterCandidate: s.beforeAfterCandidate ?? false,
      status: "indexed",
      analysisEngine: "Seeded evidence (pre-analyzed)",
      analyzedAt: `${s.date}T10:00:00.000Z`,
    };
  });
}

const [RAJ, DEL, MAH] = PROJECTS;

const rajasthan = build(RAJ, [
  {
    file: "rj-drought-baseline",
    title: "Dry, cracked ground at proposed pond site",
    description:
      "Baseline survey photo of a dry depression with deeply cracked soil and no visible surface water, recorded before water-harvesting works.",
    location: "Barmer, Rajasthan",
    activity: "Baseline site survey",
    tags: ["drought", "dry-land", "water-scarcity", "baseline", "site-survey", "cracked-soil"],
    impactAreas: ["Water Security", "Climate Resilience"],
    objects: ["cracked soil", "dry ground"],
    peopleCount: 0,
    stage: "baseline",
    date: "2026-01-12",
    confidence: 0.93,
    beforeAfterCandidate: true,
  },
  {
    file: "rj-village-baseline",
    title: "Arid village settlement before water works",
    description:
      "Wide view of a desert village with sandy terrain and sparse vegetation. No piped water infrastructure is visible in the frame.",
    location: "Phalodi, Rajasthan",
    activity: "Baseline community survey",
    tags: ["village", "arid", "desert", "baseline", "rural-settlement"],
    impactAreas: ["Water Access", "Community Development"],
    objects: ["houses", "sand", "sparse vegetation"],
    peopleCount: 0,
    stage: "baseline",
    date: "2026-01-18",
    confidence: 0.88,
    beforeAfterCandidate: true,
  },
  {
    file: "rj-water-collection",
    title: "Women carrying water from a distant source",
    description:
      "Three women carrying water pots on their heads along a village path, documenting manual water collection prior to the intervention.",
    location: "Osian, Rajasthan",
    activity: "Water collection (baseline)",
    tags: ["water-collection", "women", "community", "water-access", "baseline", "rural"],
    impactAreas: ["Water Access", "Gender Equality"],
    objects: ["water pots", "path", "people"],
    peopleCount: 3,
    stage: "baseline",
    date: "2026-01-25",
    confidence: 0.9,
  },
  {
    file: "rj-tank-construction-1",
    title: "Overhead water tank under construction",
    description:
      "Reinforced concrete columns and scaffolding for an elevated water storage tank. Construction activity is clearly visible.",
    location: "Jodhpur, Rajasthan",
    activity: "Water tank construction",
    tags: ["water-tank", "construction", "infrastructure", "scaffolding", "water-storage"],
    impactAreas: ["Water Access", "Infrastructure"],
    objects: ["scaffolding", "concrete columns", "tank structure"],
    peopleCount: 0,
    stage: "implementation",
    date: "2026-03-08",
    confidence: 0.92,
    beforeAfterCandidate: true,
  },
  {
    file: "rj-rwh-pit",
    title: "Rainwater harvesting pit being excavated",
    description:
      "Workers excavating and lining a rainwater harvesting recharge pit. Construction materials and an open trench are visible.",
    location: "Barmer, Rajasthan",
    activity: "Rainwater harvesting construction",
    tags: ["rainwater-harvesting", "construction", "groundwater-recharge", "infrastructure", "excavation"],
    impactAreas: ["Water Security", "Infrastructure", "Climate Resilience"],
    objects: ["excavation pit", "bricks", "workers"],
    peopleCount: 2,
    stage: "implementation",
    date: "2026-03-20",
    confidence: 0.86,
  },
  {
    file: "rj-tank-construction-2",
    title: "Water tank structure nearing completion",
    description:
      "Elevated tank body cast on top of the column frame, with scaffolding still partly in place around the structure.",
    location: "Jodhpur, Rajasthan",
    activity: "Water tank construction",
    tags: ["water-tank", "construction", "infrastructure", "water-storage", "pipeline"],
    impactAreas: ["Water Access", "Infrastructure"],
    objects: ["tank body", "scaffolding", "concrete frame"],
    peopleCount: 0,
    stage: "implementation",
    date: "2026-04-02",
    confidence: 0.9,
  },
  {
    file: "rj-hand-pump",
    title: "Community hand pump in daily use",
    description:
      "A hand pump installed at a community water point, with a paved platform and drainage around the base.",
    location: "Osian, Rajasthan",
    activity: "Community water point",
    tags: ["hand-pump", "borewell", "community-water-point", "drinking-water", "water-access"],
    impactAreas: ["Water Access", "Health", "Community Development"],
    objects: ["hand pump", "platform", "drain"],
    peopleCount: 1,
    stage: "completed",
    date: "2026-05-22",
    confidence: 0.94,
  },
  {
    file: "rj-tank-completed",
    title: "Completed overhead tank for rural water supply",
    description:
      "A completed elevated water tank serving a rural supply scheme. Scaffolding has been removed and the structure appears operational.",
    location: "Jodhpur, Rajasthan",
    activity: "Water storage infrastructure",
    tags: ["water-tank", "completed", "infrastructure", "rural-water-supply", "water-storage"],
    impactAreas: ["Water Access", "Infrastructure", "Community Development"],
    objects: ["overhead tank", "support columns", "pipes"],
    peopleCount: 0,
    stage: "completed",
    date: "2026-06-18",
    confidence: 0.95,
    beforeAfterCandidate: true,
  },
  {
    file: "rj-rwh-tank",
    title: "Rainwater harvesting storage tank",
    description:
      "A covered rainwater storage tank connected to rooftop collection. The structure looks newly completed.",
    location: "Phalodi, Rajasthan",
    activity: "Rainwater harvesting",
    tags: ["rainwater-harvesting", "water-tank", "water-storage", "completed", "climate-adaptation"],
    impactAreas: ["Water Security", "Climate Resilience"],
    objects: ["storage tank", "downpipe", "roof"],
    peopleCount: 0,
    stage: "completed",
    date: "2026-07-09",
    confidence: 0.87,
  },
  {
    file: "rj-check-dam",
    title: "Check dam retaining monsoon water",
    description:
      "A check dam with water overflowing its crest during the monsoon, indicating retained surface water at the structure.",
    location: "Barmer, Rajasthan",
    activity: "Check dam monitoring",
    tags: ["check-dam", "monsoon", "surface-water", "water-harvesting", "monitoring"],
    impactAreas: ["Water Security", "Climate Resilience", "Agriculture"],
    objects: ["check dam", "water", "embankment"],
    peopleCount: 0,
    stage: "monitoring",
    date: "2026-08-14",
    confidence: 0.91,
    beforeAfterCandidate: true,
  },
  {
    file: "rj-school-hand-pump",
    title: "Hand pump installed at village school",
    description:
      "Children using a hand pump within a school compound, documenting WASH-in-schools access to drinking water.",
    location: "Jodhpur, Rajasthan",
    activity: "WASH in schools",
    tags: ["school", "hand-pump", "wash", "drinking-water", "children", "sanitation"],
    impactAreas: ["Water Access", "Education", "Health"],
    objects: ["hand pump", "children", "school yard"],
    peopleCount: 4,
    stage: "completed",
    date: "2026-09-05",
    confidence: 0.89,
  },
]);

const delhi = build(DEL, [
  {
    file: "dl-dump-baseline-1",
    title: "Roadside waste dump before restoration",
    description:
      "Unmanaged solid waste piled along a roadside verge. The site shows degraded land with no vegetation cover.",
    location: "Bhalswa, New Delhi",
    activity: "Baseline site survey",
    tags: ["waste", "dumping", "pollution", "degraded-land", "baseline"],
    impactAreas: ["Waste Management", "Urban Environment"],
    objects: ["garbage", "plastic waste", "road"],
    peopleCount: 0,
    stage: "baseline",
    date: "2026-01-15",
    confidence: 0.94,
    beforeAfterCandidate: true,
  },
  {
    file: "dl-dump-baseline-2",
    title: "Unmanaged solid waste along highway edge",
    description: "Mixed municipal waste spread across open ground next to a highway, recorded during the baseline survey.",
    location: "Bhalswa, New Delhi",
    activity: "Baseline site survey",
    tags: ["waste", "dumping", "baseline", "open-dumping", "pollution"],
    impactAreas: ["Waste Management", "Public Health"],
    objects: ["garbage heap", "open ground"],
    peopleCount: 0,
    stage: "baseline",
    date: "2026-02-03",
    confidence: 0.9,
  },
  {
    file: "dl-segregation-bins",
    title: "Waste segregation bins installed in public space",
    description: "Colour-coded dry and wet waste bins installed along a public footpath to support segregation at source.",
    location: "Saket, New Delhi",
    activity: "Waste segregation infrastructure",
    tags: ["waste-collection", "segregation", "bins", "infrastructure", "recycling"],
    impactAreas: ["Waste Management", "Urban Environment"],
    objects: ["dustbins", "footpath"],
    peopleCount: 0,
    stage: "implementation",
    date: "2026-03-12",
    confidence: 0.92,
  },
  {
    file: "dl-waste-vehicles",
    title: "Segregated waste collection vehicles deployed",
    description: "A fleet of segregated waste collection vehicles at a launch event for source-segregation in the city.",
    location: "New Delhi, Delhi",
    activity: "Waste collection rollout",
    tags: ["waste-collection", "vehicles", "segregation", "municipal", "launch-event"],
    impactAreas: ["Waste Management", "Public Health"],
    objects: ["collection vehicles", "officials", "banner"],
    peopleCount: 6,
    stage: "implementation",
    date: "2026-03-28",
    confidence: 0.85,
  },
  {
    file: "dl-women-saplings",
    title: "Community members planting saplings",
    description: "Women planting saplings in prepared pits as part of a community plantation activity.",
    location: "Yamuna Floodplain, Delhi",
    activity: "Tree plantation",
    tags: ["tree-plantation", "saplings", "community", "women", "greening"],
    impactAreas: ["Biodiversity", "Climate Action", "Community Development"],
    objects: ["saplings", "planting pits", "people"],
    peopleCount: 3,
    stage: "implementation",
    date: "2026-07-06",
    confidence: 0.91,
  },
  {
    file: "dl-plantation-drive",
    title: "Families join monsoon tree plantation drive",
    description: "Families and children taking part in a tree plantation drive, planting saplings in an open area.",
    location: "Dwarka, New Delhi",
    activity: "Tree plantation drive",
    tags: ["tree-plantation", "community", "children", "volunteers", "environment-day"],
    impactAreas: ["Biodiversity", "Climate Action", "Education"],
    objects: ["saplings", "volunteers", "shovels"],
    peopleCount: 8,
    stage: "implementation",
    date: "2026-07-20",
    confidence: 0.88,
  },
  {
    file: "dl-plantation-row",
    title: "Row plantation along site boundary",
    description: "Newly planted saplings arranged in a row along a boundary, with tree guards around young plants.",
    location: "Dwarka, New Delhi",
    activity: "Tree plantation",
    tags: ["tree-plantation", "saplings", "tree-guards", "greening", "boundary"],
    impactAreas: ["Biodiversity", "Urban Environment"],
    objects: ["saplings", "tree guards"],
    peopleCount: 2,
    stage: "implementation",
    date: "2026-08-02",
    confidence: 0.86,
  },
  {
    file: "dl-urban-garden",
    title: "Landscaped urban garden with planted beds",
    description: "A landscaped public garden with planted beds, lawns and walkways, maintained as green public space.",
    location: "Saket, New Delhi",
    activity: "Urban garden development",
    tags: ["urban-garden", "green-space", "landscaping", "public-park", "completed"],
    impactAreas: ["Urban Environment", "Community Wellbeing"],
    objects: ["garden beds", "lawn", "walkway"],
    peopleCount: 0,
    stage: "completed",
    date: "2026-08-25",
    confidence: 0.9,
  },
  {
    file: "dl-restored-path",
    title: "Restored green walkway with tree cover",
    description: "A restored pedestrian walkway lined with mature trees and ground vegetation, showing established green cover.",
    location: "Lodhi Road, New Delhi",
    activity: "Restored green area",
    tags: ["restored-green-area", "tree-cover", "walkway", "green-space", "completed"],
    impactAreas: ["Urban Environment", "Biodiversity", "Community Wellbeing"],
    objects: ["trees", "walkway", "grass"],
    peopleCount: 0,
    stage: "completed",
    date: "2026-09-10",
    confidence: 0.93,
    beforeAfterCandidate: true,
  },
  {
    file: "dl-canopy",
    title: "Established tree canopy in public garden",
    description: "A mature tree with a wide canopy in a public garden, used as a monitoring reference point for green cover.",
    location: "Saket, New Delhi",
    activity: "Green cover monitoring",
    tags: ["tree-cover", "canopy", "monitoring", "green-space"],
    impactAreas: ["Biodiversity", "Climate Action"],
    objects: ["tree", "canopy", "lawn"],
    peopleCount: 0,
    stage: "monitoring",
    date: "2026-09-18",
    confidence: 0.84,
  },
]);

const maharashtra = build(MAH, [
  {
    file: "mh-school-baseline",
    title: "Rural school building before rooftop solar",
    description:
      "Hillside school building with students in the open playground. No solar equipment is visible on the roof, recorded before installation.",
    location: "Satara, Maharashtra",
    activity: "Baseline school survey",
    tags: ["school", "rural-school", "baseline", "rooftop", "education", "students"],
    impactAreas: ["Education", "Clean Energy"],
    objects: ["school building", "roof", "playground", "students"],
    peopleCount: 8,
    stage: "baseline",
    date: "2026-01-20",
    confidence: 0.87,
    beforeAfterCandidate: true,
  },
  {
    file: "mh-foundation-works",
    title: "Foundation works for solar mounting structure",
    description: "Concrete mixing at a construction site preparing foundations for ground-mounted solar structures.",
    location: "Baramati, Maharashtra",
    activity: "Site preparation",
    tags: ["construction", "foundation", "concrete", "site-preparation", "infrastructure"],
    impactAreas: ["Infrastructure", "Clean Energy"],
    objects: ["concrete mixer", "construction materials"],
    peopleCount: 1,
    stage: "implementation",
    date: "2026-03-05",
    confidence: 0.82,
  },
  {
    file: "mh-panel-install-1",
    title: "Solar PV panels being installed on roof",
    description: "Photovoltaic panels being fixed onto rooftop mounting rails. Installation is in progress.",
    location: "Satara, Maharashtra",
    activity: "Solar panel installation",
    tags: ["solar", "solar-installation", "renewable-energy", "rooftop", "installation"],
    impactAreas: ["Clean Energy", "Climate Action"],
    objects: ["solar panels", "mounting rails", "roof"],
    peopleCount: 0,
    stage: "implementation",
    date: "2026-04-10",
    confidence: 0.9,
    beforeAfterCandidate: true,
  },
  {
    file: "mh-panel-install-2",
    title: "Panels secured on mounting frames",
    description: "A completed rooftop section with solar panels secured in place on mounting frames.",
    location: "Satara, Maharashtra",
    activity: "Solar panel installation",
    tags: ["solar", "solar-installation", "clean-energy", "rooftop", "infrastructure"],
    impactAreas: ["Clean Energy", "Infrastructure"],
    objects: ["solar panels", "roof"],
    peopleCount: 0,
    stage: "implementation",
    date: "2026-04-24",
    confidence: 0.89,
  },
  {
    file: "mh-rooftop-1",
    title: "Rooftop solar panels on community buildings",
    description: "Solar panel arrays installed on the rooftops of several low-rise buildings in a residential cluster.",
    location: "Pune, Maharashtra",
    activity: "Rooftop solar deployment",
    tags: ["solar", "rooftop-solar", "renewable-energy", "community", "clean-energy"],
    impactAreas: ["Clean Energy", "Climate Action", "Community Development"],
    objects: ["solar panels", "buildings", "water tanks"],
    peopleCount: 0,
    stage: "completed",
    date: "2026-06-12",
    confidence: 0.94,
  },
  {
    file: "mh-rooftop-2",
    title: "Rooftop solar on residential cluster",
    description: "Multiple rooftops fitted with solar panels across a dense residential area.",
    location: "Pune, Maharashtra",
    activity: "Rooftop solar deployment",
    tags: ["solar", "rooftop-solar", "clean-energy", "residential", "completed"],
    impactAreas: ["Clean Energy", "Climate Action"],
    objects: ["solar panels", "houses"],
    peopleCount: 0,
    stage: "completed",
    date: "2026-06-30",
    confidence: 0.92,
  },
  {
    file: "mh-solar-array",
    title: "Ground-mounted community solar array",
    description: "Rows of ground-mounted solar panels at a community solar site, fully installed and fenced.",
    location: "Nashik, Maharashtra",
    activity: "Solar array commissioning",
    tags: ["solar", "solar-array", "renewable-energy", "clean-energy-infrastructure", "completed"],
    impactAreas: ["Clean Energy", "Infrastructure", "Climate Action"],
    objects: ["solar panels", "mounting structures", "fence"],
    peopleCount: 0,
    stage: "completed",
    date: "2026-07-22",
    confidence: 0.95,
    beforeAfterCandidate: true,
  },
  {
    file: "mh-students",
    title: "Students at solar-powered school",
    description: "School students gathered in a classroom setting at a school included in the solar programme.",
    location: "Satara, Maharashtra",
    activity: "School engagement",
    tags: ["school", "students", "education", "solar-school", "community"],
    impactAreas: ["Education", "Clean Energy"],
    objects: ["students", "classroom"],
    peopleCount: 12,
    stage: "monitoring",
    date: "2026-08-18",
    confidence: 0.83,
  },
  {
    file: "mh-solar-field",
    title: "Large solar field in operation",
    description: "An extensive solar field with long rows of panels, recorded during a routine monitoring visit.",
    location: "Baramati, Maharashtra",
    activity: "Operations monitoring",
    tags: ["solar", "solar-farm", "renewable-energy", "monitoring", "clean-energy"],
    impactAreas: ["Clean Energy", "Climate Action"],
    objects: ["solar panels", "access road"],
    peopleCount: 0,
    stage: "monitoring",
    date: "2026-09-02",
    confidence: 0.93,
  },
]);

export const SEED_ASSETS: MediaAsset[] = [...rajasthan, ...delhi, ...maharashtra];

/** Curated default before/after pairs per project. */
export const DEFAULT_PAIRS: Record<string, [string, string]> = {
  "p-rajasthan-water": ["rj-tank-construction-1", "rj-tank-completed"],
  "p-delhi-greening": ["dl-dump-baseline-1", "dl-restored-path"],
  "p-maharashtra-solar": ["mh-school-baseline", "mh-rooftop-1"],
};

export const SEED_ACTIVITY: ActivityItem[] = [
  { id: "a1", type: "analysis", message: "AI analyzed 24 new field photos", at: "2026-09-30T04:10:00.000Z", href: "/media" },
  {
    id: "a2",
    type: "project",
    message: 'Project "Rajasthan Water Access" updated',
    at: "2026-09-29T11:40:00.000Z",
    href: "/media?project=rajasthan-water-access",
  },
  { id: "a3", type: "comparison", message: "Before/after evidence detected", at: "2026-09-29T08:05:00.000Z", href: "/compare" },
  { id: "a4", type: "report", message: "Impact report generated", at: "2026-09-28T13:20:00.000Z", href: "/reports" },
  { id: "a5", type: "tags", message: "8 new sustainability tags identified", at: "2026-09-27T09:45:00.000Z", href: "/search" },
];
